project:
  title: DSA2 slides
  lib-dir: quarto_files
format:
  revealjs: 
    html-math-method: mathjax
    slide-number: true
    chalkboard: 
      buttons: true
    preview-links: auto
    logo: images/quarto.webp
    css: dsa2.css
    navigation-mode: vertical
    footer: <https://uva-cs.github.io/dsa2>
    controls: false
    template-partials:
      - title-slide.html
    toc: true
    toc-depth: 1
    toc-title: Contents
    theme: default
    menu: true
    center: false
    link-external-newwindow: true
    link-external-icon: true
